### ISSUE TITLE
Allow includePaths to change with Intellisense configuration

### ISSUE THREAD

**Issue by evanperrygrove** [jbenden/vscode-c-cpp-flylint#121]
I have a few workspaces that contain 3 or 4 different projects. They share the overwhelming majority of their code, but each one has its own folder with a different "config.h" file.

My .code-workspace file has identical settings for `C_Cpp.default.includePath` and `c-cpp-flylint.includePaths`, and then I have multiple c_cpp_properties.json files, with configurations like this:

```json
  "configurations": [
    {
      "name": "Project 1",
      "defines": [
        "${default}",
      ],
      "includePath": [
        "${default}",
        "${workspaceFolder}/../project1/config"
      ],
      "cppStandard": "c++11",
      "cStandard": "c11"
    },
    {
      "name": "Project 2",
      "defines": [
        "${default}",
        "SOME_EXTRA_MACRO"
      ],
      "includePath": [
        "${default}",
        "${workspaceFolder}/../project2/config"
      ],
      "cppStandard": "c++11",
      "cStandard": "c11"
    },
    "... (and so on. you get the idea)"
  ]
```

This allows me to switch between the projects in the workspace, and Intellisense updates its syntax highlighting and error checking appropriately. I would like to be able to do the same thing with c-cpp-flylint. Even better, if I could just tell c-cpp-flylint to use whatever `includePaths` and `defines` Intellisense is currently using, that would make life a lot easier.

**Comment by dzid26** [comment]
Oh, so based on this code:
https://github.com/jbenden/vscode-c-cpp-flylint/blob/138c5a5bbb49bf93af23cbae4d516c97b8d1631d/server/src/server.ts#L211 I see that now _c-cpp-flylint_ only takes `c_cpp_properties.json` configuration that is named `Mac`, `Linux`, `Win32`, ignoring your `"Project 1"`. 

To make it flexible, _c-cpp-flylint_ would need to somehow check `${command:cpptools.activeConfigName}` variable, instead of  `propertiesPlatform()`: https://github.com/microsoft/vscode-cpptools/pull/3219 .

**Comment by jbenden** [comment]
@dzid26 Hi! Would you be able to test the branch `activeConfigName`, to see if it meets all needs?

**Comment by jbenden** [comment]
The most recent version of the extension now includes these changes!

Should any problems arise, please feel free to re-open this bug report!

Thanks!
-Joe

**Comment by Seneral** [comment]
I assume this change is the root cause of an error I'm facing now (with C/C++ extension not installed, using clangd+CodeLLDB instead)
`Request c-cpp-flylint.cpptools.activeConfigName failed with message: command 'cpptools.activeConfigName' not found`
Is spammed continuously, and the clang linter does not work.
Enabling the microsoft C/C++ extension does fix it and clang linter does work, but I cannot do that continuously as it performs very bad and consumes gigabytes of memory.
