### ISSUE TITLE
can't use pc-lint

### ISSUE THREAD

**Issue by yanglf75** [jbenden/vscode-c-cpp-flylint#21]
i try to write the code ,but it can't work 
   "c-cpp-flylint.flexelint.executable": "c:\\lint\\lint-nt.exe ",
    "c-cpp-flylint.flexelint.configFile": ".std.lnt",

please tell me how to write it
 Thank You

**Comment by jbenden** [comment]
Hello,

Sorry, this is not enough information to assist in helping you; although I can offer a few tips:

1. The `c-cpp-flylint.flexelint.configFile` key does not function at this time. Instead of your file being named `.std.lnt`, rename it to `.flexelint.lnt`.
2. The path specified to `lint-nt.exe` is not correct JSON for the VS Code settings file - it should be specified as `c:\\lint\\lint-nt.exe`.

Best Regards and Good Luck!
-Joe
