### ISSUE TITLE
How to get this working on Windows with WSL?

### ISSUE THREAD

**Issue by shrub77** [jbenden/vscode-c-cpp-flylint#35]
I have installed Cppcheck on my ubuntu distribution for WSL. I tired changing the following setting, but it did not work. Any ideas?

`"c-cpp-flylint.cppcheck.executable": "bash -c cppcheck"`

**Comment by jbenden** [comment]
Hello,

This really isn't easily possible. Windows stores the Linux subsystem in an inaccessible to Win32 APIs location. Because of this, referencing binaries in `/usr/bin` is not possible; unless VS Code utilizes the native NT APIs (not likely.)

I recommend that you use Cygwin or MSYS2 for a `cppcheck` binary.

Best regards,
-Joe
