### ISSUE TITLE
Support for PC-lint Plus

### ISSUE THREAD

**Issue by AlataMors** [jbenden/vscode-c-cpp-flylint#64]
PC-lint and flexelint have been deprecated by Gimple (see https://www.gimpel.com/for_pclint_users.html). They have been replaced by PC-lint Plus which works on all operating systems.

The default output format has changed as have meanings of most of the error codes.

**Comment by jbenden** [comment]
Thank you for your bug report!

Yes, I have been aware of their new tooling; however, I do not have access to the software to successfully implement and test a new C/C++ Flylint plugin.

Maybe they'll run across this bug report and offer an open-source license for use in development and testing! :)

Best regards,
-Joe

**Comment by AlataMors** [comment]
Gimple offers a 30 day trial license https://www.gimpel.com/evaluate.html. In all of my email communications with them they have always been very reasonable and very well may setup an open-source license of some kind for you.

**Comment by llarose** [comment]
I've stumble upon the same problem. 

This is my configuration. 

```
//PC-LINT Plus
"c-cpp-flylint.flexelint.executable" : "C:\\Program Files\\pclp\\pclp64.exe",
"c-cpp-flylint.flexelint.enable": true,
"c-cpp-flylint.clang.enable": false,
"c-cpp-flylint.cppcheck.enable": false,
"c-cpp-flylint.flexelint.configFile": "${workspaceFolder}\\Tools\\pclp\\co-powerpc-motorola-elf-gcc.lnt",
```
Is supporting pc-lint plus is on the plug-in development roadmap ? (bug entry is almost 1 year old)

**Comment by Hairy-Lee** [comment]
> I've stumble upon the same problem.
> 
> This is my configuration.
> 
> ```
> //PC-LINT Plus
> "c-cpp-flylint.flexelint.executable" : "C:\\Program Files\\pclp\\pclp64.exe",
> "c-cpp-flylint.flexelint.enable": true,
> "c-cpp-flylint.clang.enable": false,
> "c-cpp-flylint.cppcheck.enable": false,
> "c-cpp-flylint.flexelint.configFile": "${workspaceFolder}\\Tools\\pclp\\co-powerpc-motorola-elf-gcc.lnt",
> ```
> 
> Is supporting pc-lint plus is on the plug-in development roadmap ? (github issue entry is almost 1 year old)

What file did you add this configuration to please?

**Comment by Hairy-Lee** [comment]
> I've stumble upon the same problem.
> 
> This is my configuration.
> 
> ```
> //PC-LINT Plus
> "c-cpp-flylint.flexelint.executable" : "C:\\Program Files\\pclp\\pclp64.exe",
> "c-cpp-flylint.flexelint.enable": true,
> "c-cpp-flylint.clang.enable": false,
> "c-cpp-flylint.cppcheck.enable": false,
> "c-cpp-flylint.flexelint.configFile": "${workspaceFolder}\\Tools\\pclp\\co-powerpc-motorola-elf-gcc.lnt",
> ```
> 
> Is supporting pc-lint plus is on the plug-in development roadmap ? (github issue entry is almost 1 year old)

Does this work? I have modified my settings.json file accordingly and I am still seeing the "Unable to activate Flexelint analyser" warning.

**Comment by llarose** [comment]
It does not fix the problem. I was just sharing my current configuration.
--
LAL
(514) 998-1737

**Comment by Hairy-Lee** [comment]
oh, thats dissapointing. thank you for letting me know tho.

**Comment by Hairy-Lee** [comment]
> Thank you for your bug report!
> 
> Yes, I have been aware of their new tooling; however, I do not have access to the software to successfully implement and test a new C/C++ Flylint plugin.
> 
> Maybe they'll run across this bug report and offer an open-source license for use in development and testing! :)
> 
> Best regards,
> -Joe

Hi @jbenden ,

Do you have an idea of the amount of work required to implement a plug-in for PC-Lint Plus? It would be really useful if the extension supported this latest version so given it looks like I'm going to be in lockdown again I'm happy to volunteer some help. At the very least I have a PC-Lint Plus license so could assit with testing.

**Comment by AlataMors** [comment]
@jbenden I am also interested in helping. I have license, but I have no experience in typescript or vscode extensions.

**Comment by jbenden** [comment]
Hello,

I could possibly handle the typescript part; however, to even begin, the following needs done (from someone with the software!):

1. Determination of program name. (what's the command to run?)
2. Determination of proper command-line arguments to pass.
   - The flag to enable a fixed output format of warnings, info, errors the tool produces. This ideally uses GCC output style.
   - The flag to ensure tool exits with error when errors are in fact present.
   - Any other flags that are required.
3. For the above flags, keep it minimal. People can and will customize, but the scanner needs a fixed output format.

This is the basics, though there is probably more once someone/I dig in to write the typescript.

Best regards,
-Joe

**Comment by Hairy-Lee** [comment]
Hi Joe,

Thats great, thank you. I will come back to you over the next couple of days with the answers. I assume adding them to this thread will be acceptable?

HL

**Comment by AlataMors** [comment]
Joe,

I've attached a copy of the new [manual.pdf](https://github.com/jbenden/vscode-c-cpp-flylint/files/5757655/manual.pdf).

Gimple provides the binaries for all OS's so the command changes depending on the host OS.
- pclp64_linux
- pclp64_macos
- pclp32.exe
- pclp64.exe

Message format flags are in the manual at 4.3.3 on starting on page 54.
There are several flags that work together to set the output format.
- -h Sets the message height in lines.
- -format* Sets the format of the message, but depends on what -h is set to.
- -width sets line width and breaking.
I'll look into finding a specific set of options for a gcc style fomat. Unless HL beats me to it.

By default the exit code is 0, unless lint cannot finish the job in which case it is 1.
The -frz flag will make the exit code return the number of lint messages generated. 

Hope this helps with getting things started,
-AlataMors

**Comment by Hairy-Lee** [comment]
Thanks AlataMors, gcc output style is:

-"format=%(%f:%l:%c: %)%t %n: %m"

this produces messages in the following format:

C:/source/filter_test.h:9:99: info 783: line does not end with a newline

Not sure about height and width, tho thought I best actually contribute something :) 

Happy New Year all.

**Comment by jbenden** [comment]
Hello all,

First off, Happy New Year!

Next up, I got the code written. See PR #93 for the code.

If possible, could you test this code out, prior to me publishing a new release? You should be able to clone this repository inside VS Code and open a debugging session, which would allow testing. If that's all to complex, I could create a .vsix to install...

Before testing, you'll want to configure at minimum the following:

```
{
 "c-cpp-flylint.pclintplus.enable": true,
 "c-cpp-flylint.pclintplus.executable": "../path/and/programname",
 "c-cpp-flylint.pclintplus.configFile": "project's .lnt filename or accept the default one"
}
```

Best of luck!
-Joe

**Comment by Hairy-Lee** [comment]
Thats great, thanks Joe.

Please bear with me as I'm relatively new to visual studio code and GitHub. I've cloned the repository and checked out the pclintplus branch via GitHub Desktop. From here I used the option to open the repository in VS Code. I then configured settings.json as recommended. Hit F5 to start debugging and received the folowing in the terminal:

[terminal.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5760309/terminal.txt)

I then got a pop-up warning me that "The preLaunchTask 'npm: vscode:prepublish' terminated with exit code 1." It gave me the option to "Debug Anyway" which I selected and this opened up another VS Code window with the example source that I had been using to test your extension. However, there was a warning stating "Activating extension 'jbenden.c-cpp-flylint' failed: Cannot find module 'c:\github\vscode-c-cpp-flylint\dis\extension.js'

Any suggestions, I have npm added to my PATH variable.

**Comment by jbenden** [comment]
Hi!

The problem is that the tool `webpack` could not be found anywhere.

I have pushed new changes to that branch (you must delete and re-checkout the branch) that may help Windows to find the webpack tool.

Please give that a try and let me know how it goes!

Thank you!
-Joe

**Comment by Hairy-Lee** [comment]
Hey,

Still no joy I'm afraid as I get the same errors. I suspected that webpack was the issue so had a quick look stackoverflow reported this [https://stackoverflow.com/questions/35810172/webpack-is-not-recognized-as-a-internal-or-external-command-operable-program-or](url) hence my comment wrt npm being added to PATH. I have also run `npm install webpac` I didn't pass it the -g flag though. Should I?

Cheers,

HL

**Comment by jbenden** [comment]
Hello,

No worries, we'll figure it out!

## Short Story

So, the short story is within VS Code, open a terminal, then at the project root (the default when terminal opens) run:

```
npm i
```

Afterwards, pressing `F5` to run the debugging version of the extension worked!

## Long Story

I went and downloaded a Windows VMDK from Microsoft, within their developer tools.

Launched this VMDK inside of VirtualBox.

Next, I installed the following set of tools:

- VS Code x64
- Git for Windows x64
- Node.js 12.x for x64 (inside of "Past Releases" on their download page) I went with 12.x because it's what I've been using on Linux.
   - When installing Node.js, I did check the box to install the compilation tools for building modules. This installed Chocolatey, Python, VS, runtime redistribs, etc.

Next, I opened VS Code and selected to open a repository - and filled it out for this project.

At this point, if I pressed `F5` I would be met with the `webpack` can not be found error.

So, I opened Terminal view and ran `npm i` at the prompt. It went and installs everything used by the extension.

Now, pressing `F5` does properly launch a new window with the extension present.

I hope this all helps,
-Joe

**Comment by Hairy-Lee** [comment]
Success, well over the 1st hurdle `npm i` worked and I'm able to open a debug session. However, I get a warning notification pop up when the debug window opens stating "Unable to activate PclintPlus analyzer."

my settings.json includes:

`
{
"c-cpp-flylint.pclintplus.enable": true,
"c-cpp-flylint.pclintplus.executable" : "C:\\pclp-1.3.5\\windows\\pclp64.exe",
"c-cpp-flylint.pclintplus.configFile": "C:\\pclp-1.3.5\\windows\\config\\co-xc16.lnt",
}
`

Are there any log files that you need me to dig out?

**Comment by jbenden** [comment]
Hi,

Glad that the first hurdle is over. :)

I ran some local testing, and the configuration that locally worked was:

```
{
  "c-cpp-flylint.clang.enable": false,
  "c-cpp-flylint.cppcheck.enable": false,
  "c-cpp-flylint.debug": true,
  "c-cpp-flylint.flexelint.enable": false,
  "c-cpp-flylint.pclintplus.enable": true,
  "c-cpp-flylint.run": "onType",
  "c-cpp-flylint.pclintplus.executable" : "C:\\pclp-1.3.5\\windows\\pclp64.exe",
  "c-cpp-flylint.pclintplus.configFile": "C:\\pclp-1.3.5\\windows\\config\\co-xc16.lnt"
}
```

Adding that `debug` flag should also help. Under `View` -> `Output` there is a drop-down box with logging sources. Select the one with `C/C++ Flylint`.

I will always need the information from that log when troubleshooting.

Best regards,
-Joe

**Comment by Hairy-Lee** [comment]
Morning Joe,

Yes, progress is a good thing :)

I switched to using the configuration you stated above but I stoll get the Unable to activate PclintPlus analyzer. notification. The output I get is as follows:

`Debugger listening on ws://127.0.0.1:6011/0d2d6823-3b5f-4c48-a2d6-a66cbb5e92e9`
`For help, see: https://nodejs.org/en/docs/inspector`
`Performing lint scan of c:\Users\HairyLee\source\repos\Array\mainXC16.c...`
`Completed lint scans...`
`Performing lint scan of c:\Users\HairyLee\source\repos\Array\mainXC16.c...`
`Skipping PclintPlus linter because lintOn 1 is not in 2.`
`Completed lint scans...`

I tried setting `"c-cpp-flylint.run": "onSave",` but this made no difference and observing the output window it seemed like the scan was still being carried out according to `onType`.

Thanks,

HL

**Comment by jbenden** [comment]
Hello,

I found one problem which I've resolved. Namely, the use of absolute paths for configuration files (key `"c-cpp-flylint.pclintplus.configFile"`).

It turns out the code was not logging any message when it failed to locate a configuration file. Additionally, the code did not handle absolute files, at all.

I have made changes to the PR to account for this bug. Please delete and re-checkout the branch, then test again.

Thank for your time and patience,
-Joe

**Comment by Hairy-Lee** [comment]
Hi,

Not a problem, more than happy to help; thank you for your effort.

Initially I observed an issue within the output window [Output1.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5775455/Output1.txt)

This was regarding an inclusion of an indirect file (me-project.lnt) contained within my co-xc16.lnt file [co-xc16.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5775442/co-xc16.txt) (file extension changed so that I can attach it). This file is located in C:\pclp-1.3.5\windows\lnt which as you can see is specified within my compiler options file. I also received a notification pop-up [Notification1.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5775472/Notification1.txt). 

I removed the indirect file and observed the following within the output window [Output2.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5775483/Output2.txt). Again I also received a notification pop-up [Notification2.txt](https://github.com/jbenden/vscode-c-cpp-flylint/files/5775485/Notification2.txt). I assume this is telling me that the extension wasn't abe to parse the output from PC-Lint Plus to the Problem window as nothing was observed in this window.

Cheers,

HL

**Comment by jbenden** [comment]
Hi!

I actually expected issues with the parsing; to be honest. I didn't really have true example outputs...

So, I've made a number of changes, integrating the outputs given in to unit-tests, and now everything parses as I'd expect.

Would you please delete and re-checkout the branch, then test again.

Thank you for your time and patience,
-Joe

**Comment by Hairy-Lee** [comment]
Hello,

I’m pleased to report success, of a sorts. 

Initially when I ran the debugger the only difference that I observed was that I no longer saw the pop-up notification, but I still wasn’t seeing the issues that PC-Lint Plus detected being displayed in the Output window parsed to the Problem window. 

I made a minor change to my file and observed the Output window where I subsequently saw `Skipping PclintPlus linter because lintOn 1 is not in 2.` I then reverted this with “ctrl+z” and again saw the same message.

I modified settings.json to disable PC-Lint Plus and instead enabled CppCheck to confirm that the issues it detected did still parse, which it did after I saved settings.json. When I changed settings.json back it sprang into life and I got all the issues from PC-Lint Plus dumped into my Problems window. Woohoo! 

A couple of observations:

1. It would seem OnType isn’t working, I only saw something in the Problem window once I hit save. This is the case for both CppCheck and PC-Lint Plus.

2. It is still objecting to the inclusion of an indirect file, but I’m not sure if this is you or me. If I run PC-Lint Plus in MPLABX it doesn’t complain until I comment out the indirect file as it contains project specific definitions. The output message is the same as the one I reported to you yesterday in Output1.txt.

**Comment by Hairy-Lee** [comment]
Looks like the inclusion of an indirect file issue is one for me to sort out, just tried it with another IDE and I get the same issue. Odd that its fine with MPLABX.

**Comment by jbenden** [comment]
Hi,

Thanks for the report!

On the inclusion of an indirect file, the problem could be related to working directory. It may be the working directory, within the editor, is completely not what is needed. Could you switch to using absolute paths for them?

For run type, it is a way of the linters supporting file io changes and/or key typing changes. Not all of the linters support the later, so when that event occurs the linters are skipped. This is the case with the message seen, `Skipping PclintPlus linter because lintOn 1 is not in 2.` the `lintOn` equal to 1 is on file io and the `lintOn` equal to 2 is for key typing changes. Additionally, the only linter that does support 2 (`onType`) is Clang.

If you still believe there to be an error condition, please record the initial starting state of `c-cpp-flylint.run` followed by all steps taken that lead to the error being realized.

Thanks for all the help building this!
-Joe

**Comment by Hairy-Lee** [comment]
Hi,

Not a problem, thanks for being so proactive in making the changes.

No I think we're all good, it was just my lack of understanding of how your code worked. Thanks for the explanation. I've just run through things again and it looks good all the problems output by PC Lint Plus are being parsed through to the Problems window and it will take you to the offending line in the code.

I've got some design documentation to do then I should be using VS Code it in anger later in the month so will have a better opportunity to stress test the extension. I'll feed back any further observations.

I'll leave you to push out a release :)

Cheers,

HL
